name: sleep_time_picker
description: A customizable sleep time picker.
author: Mohammad Saiful Islam
version: 1.0.0
homepage: https://github.com/mohammadsaif19/sleep_time_picker
repository: https://github.com/mohammadsaif19/sleep_time_picker
issue_tracker: https://github.com/mohammadsaif19/sleep_time_picker/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
